# Generated by Django 5.2.7 on 2025-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("domain_name", models.CharField(max_length=100, unique=True)),
                ("max_users", models.IntegerField(default=10)),
                ("max_storage_gb", models.IntegerField(default=50)),
                ("current_users", models.IntegerField(default=0, editable=False)),
                ("storage_used_mb", models.IntegerField(default=0, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
    ]
