# Generated by Django 5.2.7 on 2025-11-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=253, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("domain", "Primary Domain"),
                            ("relaydomain", "Relay Domain"),
                            ("aliasdomain", "Alias Domain"),
                        ],
                        default="domain",
                        max_length=20,
                    ),
                ),
                (
                    "quota",
                    models.IntegerField(
                        default=0, help_text="Domain quota in MB (0 = unlimited)"
                    ),
                ),
                (
                    "default_mailbox_quota",
                    models.IntegerField(
                        default=1024, help_text="Default mailbox quota in MB"
                    ),
                ),
                (
                    "message_limit",
                    models.IntegerField(
                        default=0, help_text="Messages per hour (0 = unlimited)"
                    ),
                ),
                ("antivirus", models.BooleanField(default=True)),
                ("antispam", models.BooleanField(default=True)),
                (
                    "spam_threshold",
                    models.IntegerField(default=5, help_text="Spam score threshold"),
                ),
                ("dkim_enabled", models.BooleanField(default=True)),
                ("dkim_selector", models.CharField(default="mail", max_length=100)),
                ("dkim_private_key", models.TextField(blank=True, null=True)),
                ("dkim_public_key", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("quota_mb", models.IntegerField(default=1024)),
                ("usage_mb", models.IntegerField(default=0, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="mail.domain",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="EmailFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("unread_count", models.IntegerField(default=0, editable=False)),
                ("total_count", models.IntegerField(default=0, editable=False)),
                ("is_special", models.BooleanField(default=False)),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("sent", "Sent"),
                            ("drafts", "Drafts"),
                            ("trash", "Trash"),
                            ("spam", "Spam"),
                            ("archive", "Archive"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="mail.emailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Folder",
                "verbose_name_plural": "Email Folders",
                "ordering": ["name"],
                "unique_together": {("account", "name")},
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("uid", models.CharField(blank=True, max_length=100, null=True)),
                ("subject", models.TextField()),
                ("sender", models.EmailField(max_length=254)),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("to_recipients", models.JSONField()),
                ("cc_recipients", models.JSONField(default=list)),
                ("bcc_recipients", models.JSONField(default=list)),
                ("body_text", models.TextField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True, null=True)),
                ("date_sent", models.DateTimeField()),
                ("date_received", models.DateTimeField(auto_now_add=True)),
                ("size_bytes", models.IntegerField(default=0)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("flags", models.JSONField(default=list)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mail.emailaccount",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mail.emailfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.IntegerField()),
                ("attachment_file", models.FileField(upload_to="email_attachments/")),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_inline", models.BooleanField(default=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mail.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["account", "folder", "date_received"],
                name="mail_emailm_account_2396d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["account", "is_read"], name="mail_emailm_account_abd657_idx"
            ),
        ),
    ]
