# Generated by Django 4.2.7 on 2025-11-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainDKIM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("selector", models.CharField(default="mail", max_length=100)),
                ("private_key", models.TextField(blank=True, null=True)),
                ("public_key", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Domain DKIM",
                "verbose_name_plural": "Domain DKIMs",
            },
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="mail_emailm_account_2396d6_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="mail_emailm_account_abd657_idx",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="dkim_enabled",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="dkim_private_key",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="dkim_public_key",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="dkim_selector",
        ),
        migrations.RemoveField(
            model_name="emailmessage",
            name="account",
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["folder", "date_received"],
                name="mail_emailm_folder__0056ef_idx",
            ),
        ),
        migrations.AddField(
            model_name="domaindkim",
            name="domain",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dkim_config",
                to="mail.domain",
            ),
        ),
    ]
