# Generated by Django 4.2.7 on 2025-11-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_domaindkim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mail.emailaccount",
            ),
        ),
    ]
