# Generated by Django 5.2.7 on 2025-11-12 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_contact_alter_emailmessage_account_task_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='account',
        ),
        migrations.RemoveField(
            model_name='emailsignature',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.emailmessage'),
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='organization',
        ),
    ]
