# Generated by Django 5.2.7 on 2025-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_remove_organization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Password hash for Dovecot authentication', max_length=255, null=True),
        ),
    ]
